// ─── TRADE-SPECIFIC LICENSE DATA — ALL 5 TRADES × ALL 50 STATES ─────────────
// Covers: Plumber, Electrician, HVAC, Roofing, Specialty
// Last updated: April 2026
// Source: State licensing boards, NASCLA, ServiceTitan, NextInsurance, ContractorMatrix

export const TRADE_LICENSE_DATA = {

  // ─── PLUMBER ───────────────────────────────────────────────────────────────
  Plumber: {
    "Alabama": { required: true, licenseType: "Journeyman + Master Plumber", board: "Alabama Plumbers & Gas Fitters Examining Board", website: "alabamaplumbers.com", notes: "2 yrs apprentice → Journeyman. 1 yr Journeyman → Master." },
    "Alaska": { required: true, licenseType: "Mechanical Administrator (Plumbing)", board: "AK Dept. of Labor & Workforce Development", website: "labor.alaska.gov", notes: "Also requires contractor license from DCCED." },
    "Arizona": { required: true, licenseType: "C-37 Plumbing Contractor (Residential R-37 or Commercial)", board: "Arizona Registrar of Contractors (ROC)", website: "roc.az.gov", notes: "No journeyman license statewide — contractor license only. Some cities license journeymen." },
    "Arkansas": { required: true, licenseType: "Journeyman + Master Plumber + Plumbing Contractor", board: "AR Dept. of Health, Plumbing & Natural Gas Division", website: "healthy.arkansas.gov", notes: "Must employ licensed master plumber. 5 yrs experience for master." },
    "California": { required: true, licenseType: "C-36 Plumbing Contractor License", board: "CA Contractors State License Board (CSLB)", website: "cslb.ca.gov", notes: "4 yrs journeyman experience required. $15,000 bond. $1,000+ project threshold." },
    "Colorado": { required: true, licenseType: "Plumber License (state-issued)", board: "CO DORA Division of Professions & Occupations", website: "dora.colorado.gov", notes: "State licenses plumbers unlike GC. Local permits also required." },
    "Connecticut": { required: true, licenseType: "Apprentice / Journeyman / Master Plumber", board: "CT Dept. of Consumer Protection", website: "portal.ct.gov/DCP", notes: "Must be master plumber to work independently as contractor." },
    "Delaware": { required: true, licenseType: "Journeyman + Master Plumber (Resident or Non-Resident)", board: "Delaware Board of Plumbing Examiners", website: "dpr.delaware.gov", notes: "Biennial renewal. No formal reciprocity." },
    "Florida": { required: true, licenseType: "Certified Plumbing Contractor (CPC) or Registered", board: "FL DBPR — Construction Industry Licensing Board", website: "myfloridalicense.com", notes: "Certified = statewide. Registered = local only. $100,000 GL + $25,000 property damage required." },
    "Georgia": { required: true, licenseType: "Plumber License (all levels required)", board: "GA State Construction Industry Licensing Board", website: "sos.ga.gov/plb", notes: "All plumbers must be licensed even under a master plumber." },
    "Hawaii": { required: true, licenseType: "Journeyman + Master Plumber (Specialty Contractor)", board: "Hawaii DCCA Contractors License Board", website: "cca.hawaii.gov/pvl", notes: "No reciprocity with any state." },
    "Idaho": { required: true, licenseType: "Plumbing Contractor License", board: "Idaho Division of Building Safety", website: "dbs.idaho.gov", notes: "State licenses plumbers despite no GC license. Journeyman + contractor levels." },
    "Illinois": { required: true, licenseType: "Licensed Plumber (state-issued)", board: "IL Capital Development Board", website: "illinois.gov/cdb", notes: "State-licensed unlike GC. Local registration may also be required." },
    "Indiana": { required: true, licenseType: "Journeyman Plumber + Plumbing Contractor", board: "Indiana Plumbing Commission", website: "in.gov/pla", notes: "No master plumber — highest level is Plumbing Contractor. 4 yrs experience required." },
    "Iowa": { required: true, licenseType: "Journeyman + Master Plumber", board: "Iowa Plumbing & Mechanical Systems Board", website: "plumbing.iowa.gov", notes: "Reciprocity with MN, NE, SD for journeyman and master levels." },
    "Kansas": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "Kansas State Board of Technical Professions", website: "ksbtp.ks.gov", notes: "State licenses plumbers despite no GC license requirement." },
    "Kentucky": { required: true, licenseType: "Journeyman + Master Plumber", board: "KY Dept. of Housing, Buildings & Construction", website: "dhbc.ky.gov", notes: "Reciprocity with WV, OH, IN, TN with local code exam." },
    "Louisiana": { required: true, licenseType: "Journeyman + Master Plumber + Plumbing Contractor", board: "Louisiana State Plumbing Board", website: "lspb.la.gov", notes: "Aug 2025: contractor license required for $10,000+ projects. Must employ master plumber." },
    "Maine": { required: true, licenseType: "Journeyman + Master Plumber", board: "Maine Dept. of Professional & Financial Regulation", website: "maine.gov/pfr/professionallicensing", notes: "State licenses plumbers. Local permits required for work over $3,000." },
    "Maryland": { required: true, licenseType: "Journeyman + Master Plumber + HVACR Contractor", board: "Maryland Board of Plumbing + Dept. of Labor", website: "dllr.state.md.us", notes: "Plumbing contractor license required for residential under MHIC." },
    "Massachusetts": { required: true, licenseType: "Apprentice / Journeyman / Master Plumber", board: "MA Board of State Examiners of Plumbers & Gas Fitters", website: "mass.gov/plumbing", notes: "Master required to contract independently." },
    "Michigan": { required: true, licenseType: "Journeyman + Master Plumber + Mechanical Contractor", board: "Michigan LARA — Bureau of Construction Codes", website: "michigan.gov/lara", notes: "Some cities require additional registration." },
    "Minnesota": { required: true, licenseType: "Journeyman + Master Plumber + Plumbing Contractor", board: "MN Dept. of Labor & Industry", website: "dli.mn.gov", notes: "Reciprocity with ND, SD. $25,000 surety bond required." },
    "Mississippi": { required: true, licenseType: "Journeyman + Master Plumber + Plumbing Contractor", board: "Mississippi State Board of Contractors", website: "msboc.us", notes: "State license required for $10,000+ residential, $50,000+ commercial." },
    "Missouri": { required: false, licenseType: "Local jurisdiction only (no state license)", board: "Local City/County", website: "N/A", notes: "St. Louis, Kansas City have local plumber licensing. EPA 608 required for refrigerants." },
    "Montana": { required: true, licenseType: "Journeyman + Master Plumber", board: "MT Dept. of Labor & Industry, Board of Plumbers", website: "ebiz.mt.gov/pol", notes: "State licenses plumbers. Workers' comp required if you have employees." },
    "Nebraska": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "Nebraska Dept. of Health & Human Services", website: "dhhs.ne.gov", notes: "Reciprocity with IA, MN, SD for journeyman and master." },
    "Nevada": { required: true, licenseType: "Plumbing Contractor (covered under general contractor license)", board: "Nevada State Contractors Board (NSCB)", website: "nscb.nv.gov", notes: "C-1D Plumbing and Heating specialty classification." },
    "New Hampshire": { required: true, licenseType: "Journeyman + Master Plumber", board: "NH Office of Professional Licensure & Certification", website: "oplc.nh.gov", notes: "State licenses plumbers despite no GC license." },
    "New Jersey": { required: true, licenseType: "Plumbing Contractor License", board: "NJ Dept. of Community Affairs — Division of Codes", website: "nj.gov/dca", notes: "Must employ licensed master plumber." },
    "New Mexico": { required: true, licenseType: "Journeyman + Master Plumber + PJ-1 Contractor", board: "NM Regulation & Licensing Dept. — Construction Industries Division", website: "rld.state.nm.us/construction", notes: "PJ-1 license required for plumbing contracting." },
    "New York": { required: true, licenseType: "Master Plumber License (NYC and local jurisdictions)", board: "NYC Dept. of Buildings + Local Boards", website: "nyc.gov/buildings", notes: "No statewide plumber license. NYC requires separate master plumber license. $50,000 insurance required in NYC." },
    "North Carolina": { required: true, licenseType: "Plumbing Contractor License", board: "NC State Board of Examiners of Plumbing, Heating & Fire Sprinkler Contractors", website: "ncbephfsc.org", notes: "Separate from GC license." },
    "North Dakota": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "ND State Plumbing Board", website: "plumbingboard.nd.gov", notes: "Low threshold — $4,000 triggers requirement." },
    "Ohio": { required: true, licenseType: "Plumbing Contractor (OCILB)", board: "Ohio Construction Industry Licensing Board (OCILB)", website: "com.ohio.gov/ocilb", notes: "State licenses plumbers via OCILB despite no statewide GC license." },
    "Oklahoma": { required: true, licenseType: "Journeyman + Master Plumber", board: "Oklahoma Construction Industries Board", website: "cib.ok.gov", notes: "State plumber license required despite no GC license." },
    "Oregon": { required: true, licenseType: "Journeyman + Supervising Plumber + Contractor (CCB)", board: "Oregon Construction Contractors Board (CCB) + State Plumbing Board", website: "oregon.gov/ccb", notes: "Dual licensing — CCB for contracting, Plumbing Board for trade." },
    "Pennsylvania": { required: true, licenseType: "Master Plumber License (local jurisdictions)", board: "Local City/County + Philadelphia Dept. of L&I", website: "N/A", notes: "No statewide plumber license. Philadelphia requires separate master plumber license." },
    "Rhode Island": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "RI Contractors' Registration & Licensing Board", website: "crb.ri.gov", notes: "All levels licensed at state level." },
    "South Carolina": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "SC Contractor's Licensing Board", website: "llr.sc.gov/clb", notes: "NASCLA member. Contractor must employ licensed master plumber." },
    "South Dakota": { required: true, licenseType: "Journeyman + Master Plumber", board: "SD Dept. of Labor & Regulation", website: "dlr.sd.gov", notes: "State licenses plumbers despite no GC license." },
    "Tennessee": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "TN Dept. of Commerce & Insurance", website: "tn.gov/commerce", notes: "NASCLA member. $25,000+ commercial projects need contractor license." },
    "Texas": { required: true, licenseType: "Journeyman + Master Plumber + Responsible Master Plumber (RMP)", board: "Texas State Board of Plumbing Examiners (TSBPE)", website: "tsbpe.texas.gov", notes: "Despite no GC state license, plumbers MUST have state license. RMP required to run a plumbing business." },
    "Utah": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "Utah Division of Occupational & Professional Licensing (DOPL)", website: "dopl.utah.gov", notes: "NASCLA member." },
    "Vermont": { required: true, licenseType: "Master Plumber + Plumbing Contractor", board: "VT Office of Professional Regulation", website: "sos.vermont.gov/opr", notes: "State licenses plumbers despite no GC license." },
    "Virginia": { required: true, licenseType: "Journeyman + Master Plumber + Class A/B/C Contractor", board: "VA Board for Contractors (DPOR)", website: "dpor.virginia.gov", notes: "NASCLA member. Plumber license separate from GC license." },
    "Washington": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "WA Dept. of Labor & Industries", website: "lni.wa.gov", notes: "Plumber license administered separately from GC registration." },
    "West Virginia": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "WV Division of Labor", website: "labor.wv.gov", notes: "Reciprocity with KY, VA, OH for master plumber." },
    "Wisconsin": { required: true, licenseType: "Journeyman + Master Plumber + Contractor", board: "WI Dept. of Safety & Professional Services (DSPS)", website: "dsps.wi.gov", notes: "All levels state licensed." },
    "Wyoming": { required: true, licenseType: "Journeyman + Master Plumber", board: "WY Dept. of Fire Prevention & Electrical Safety", website: "wyomingfireelectric.com", notes: "State licenses plumbers despite no GC license." },
    "Washington D.C.": { required: true, licenseType: "Journeyman + Master Plumber", board: "DC Dept. of Consumer & Regulatory Affairs (DCRA)", website: "dcra.dc.gov", notes: "8,000 hours documented experience required for journeyman." },
  },

  // ─── HVAC ──────────────────────────────────────────────────────────────────
  HVAC: {
    "Alabama": { required: true, licenseType: "HVAC Contractor License", board: "Alabama Board of Heating, Air Conditioning & Refrigeration Contractors", website: "abha.alabama.gov", notes: "3,000 hrs experience + exam. $20,000 performance bond. EPA 608 required." },
    "Alaska": { required: true, licenseType: "Mechanical Administrator License", board: "AK Dept. of Commerce, Community & Economic Development", website: "commerce.alaska.gov", notes: "No separate HVAC technician license. EPA 608 required for refrigerants." },
    "Arizona": { required: true, licenseType: "HVAC Contractor License (ROC)", board: "Arizona Registrar of Contractors (ROC)", website: "roc.az.gov", notes: "Technicians work under licensed contractor. EPA 608 required. $330–$630 license cost." },
    "Arkansas": { required: true, licenseType: "HVAC Contractor License", board: "AR Dept. of Health", website: "healthy.arkansas.gov", notes: "Journeyman + contractor levels. EPA 608 required. 3–5 year apprenticeship." },
    "California": { required: true, licenseType: "C-20 HVAC/Sheet Metal Contractor License", board: "CA Contractors State License Board (CSLB)", website: "cslb.ca.gov", notes: "4 yrs experience required. Technicians need EPA 608 but no state tech license." },
    "Colorado": { required: false, licenseType: "Local jurisdiction only — EPA 608 required statewide", board: "Local City/County", website: "N/A", notes: "No state HVAC license. Denver, Boulder have local requirements. EPA 608 federal requirement applies." },
    "Connecticut": { required: true, licenseType: "S-1 Heating, Piping & Cooling Contractor", board: "CT Dept. of Consumer Protection", website: "portal.ct.gov/DCP", notes: "Apprentice, journeyman, and contractor levels." },
    "Delaware": { required: true, licenseType: "HVAC Contractor License", board: "Delaware Division of Revenue", website: "revenue.delaware.gov", notes: "EPA 608 required in addition to state license." },
    "Florida": { required: true, licenseType: "Certified HVAC Contractor or Registered", board: "FL DBPR — Construction Industry Licensing Board", website: "myfloridalicense.com", notes: "Certified = statewide. Registered = local only. $100,000 GL required." },
    "Georgia": { required: true, licenseType: "HVAC Contractor License", board: "GA State Construction Industry Licensing Board", website: "sos.ga.gov/plb", notes: "Exam required. EPA 608 required." },
    "Hawaii": { required: true, licenseType: "Specialty Contractor — HVAC", board: "Hawaii DCCA Contractors License Board", website: "cca.hawaii.gov/pvl", notes: "Covered under specialty contractor classification." },
    "Idaho": { required: true, licenseType: "HVAC Contractor License", board: "Idaho Division of Building Safety", website: "dbs.idaho.gov", notes: "State HVAC license despite no GC license. EPA 608 required." },
    "Illinois": { required: true, licenseType: "HVAC Contractor License (state-issued)", board: "IL Dept. of Public Health", website: "dph.illinois.gov", notes: "State licenses HVAC unlike GC. Local registration may also apply." },
    "Indiana": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "No state HVAC license. Check local requirements." },
    "Iowa": { required: true, licenseType: "Mechanical Contractor License", board: "Iowa Plumbing & Mechanical Systems Board", website: "plumbing.iowa.gov", notes: "EPA 608 required. State license for HVAC contractors." },
    "Kansas": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "No state HVAC license. Wichita has local requirements." },
    "Kentucky": { required: true, licenseType: "HVAC Contractor License", board: "KY Dept. of Housing, Buildings & Construction", website: "dhbc.ky.gov", notes: "Journeyman and contractor levels. EPA 608 required." },
    "Louisiana": { required: true, licenseType: "HVAC Contractor License", board: "Louisiana State Licensing Board for Contractors (LSLBC)", website: "lslbc.louisiana.gov", notes: "Must employ licensed HVAC mechanic. EPA 608 required." },
    "Maine": { required: true, licenseType: "Master Technician License (per fuel type)", board: "Maine Dept. of Professional & Financial Regulation", website: "maine.gov/pfr", notes: "Separate licenses for oil, propane, natural gas. EPA 608 required." },
    "Maryland": { required: true, licenseType: "Journeyman + Master HVACR + Contractor", board: "Maryland Board of HVACR Contractors", website: "dllr.state.md.us/license/hvacr", notes: "6 license types: Master, Master Restricted, Limited Contractor, Journeyman, Journeyman Restricted, Apprentice." },
    "Massachusetts": { required: true, licenseType: "Refrigeration Contractor License (for 10+ tons)", board: "MA Board of Examiners of Sheet Metal Workers", website: "mass.gov", notes: "No general HVAC tech license. Refrigeration license required for large systems. EPA 608 statewide." },
    "Michigan": { required: true, licenseType: "Mechanical Contractor License", board: "Michigan LARA — Bureau of Construction Codes, Mechanical Division", website: "michigan.gov/lara", notes: "Multiple specialty classifications. EPA 608 required." },
    "Minnesota": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "Minneapolis and St. Paul require local HVAC contractor certification. No state license." },
    "Mississippi": { required: true, licenseType: "HVAC Contractor License", board: "Mississippi State Board of Contractors", website: "msboc.us", notes: "Required for $10,000+ residential, $50,000+ commercial. EPA 608 required." },
    "Missouri": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "No state HVAC license. St. Louis and Kansas City have local requirements." },
    "Montana": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "No state HVAC license." },
    "Nebraska": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "Omaha and Lincoln have local requirements." },
    "Nevada": { required: true, licenseType: "HVAC Contractor License (ROC)", board: "Nevada State Contractors Board", website: "nscb.nv.gov", notes: "C-21 classification for HVAC. EPA 608 required." },
    "New Hampshire": { required: true, licenseType: "HVAC Contractor License", board: "NH Office of Professional Licensure & Certification", website: "oplc.nh.gov", notes: "EPA 608 required." },
    "New Jersey": { required: true, licenseType: "HVACR Contractor License", board: "NJ Dept. of Community Affairs", website: "nj.gov/dca", notes: "EPA 608 required." },
    "New Mexico": { required: true, licenseType: "MM-1 Mechanical Contractor License", board: "NM Construction Industries Division", website: "rld.state.nm.us/construction", notes: "Covers HVAC and plumbing." },
    "New York": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "NYC has local HVAC contractor requirements. No statewide HVAC license." },
    "North Carolina": { required: true, licenseType: "HVAC Contractor License", board: "NC Board of Heating and Air Conditioning Contractors", website: "ncbhac.org", notes: "Separate from plumbing/electrical. EPA 608 required." },
    "North Dakota": { required: true, licenseType: "HVAC Contractor License", board: "ND State Plumbing Board", website: "plumbingboard.nd.gov", notes: "EPA 608 required." },
    "Ohio": { required: true, licenseType: "HVAC Contractor License (OCILB)", board: "Ohio Construction Industry Licensing Board (OCILB)", website: "com.ohio.gov/ocilb", notes: "State HVAC license required via OCILB. EPA 608 required." },
    "Oklahoma": { required: true, licenseType: "HVAC Contractor License", board: "Oklahoma Construction Industries Board", website: "cib.ok.gov", notes: "EPA 608 required." },
    "Oregon": { required: true, licenseType: "HVAC/Refrigeration Contractor (CCB)", board: "Oregon CCB + Oregon HVAC/Refrigeration Licensing Board", website: "oregon.gov/ccb", notes: "Dual licensing. EPA 608 required." },
    "Pennsylvania": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "No statewide HVAC license. Philadelphia has local requirements." },
    "Rhode Island": { required: true, licenseType: "HVAC Contractor License", board: "RI Contractors' Registration & Licensing Board", website: "crb.ri.gov", notes: "EPA 608 required." },
    "South Carolina": { required: true, licenseType: "HVAC Contractor License", board: "SC Contractor's Licensing Board", website: "llr.sc.gov/clb", notes: "EPA 608 required. NASCLA member." },
    "South Dakota": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "No state HVAC license." },
    "Tennessee": { required: true, licenseType: "HVAC Contractor License ($25,000+ projects)", board: "TN Board for Licensing Contractors", website: "tn.gov/commerce/boards/contractors", notes: "Local licensing for journeyman/master. EPA 608 required." },
    "Texas": { required: true, licenseType: "Air Conditioning and Refrigeration (ACR) Contractor License", board: "Texas Dept. of Licensing & Regulation (TDLR)", website: "tdlr.texas.gov", notes: "Despite no GC state license, HVAC MUST have TDLR ACR license. EPA 608 required." },
    "Utah": { required: true, licenseType: "HVAC Contractor License", board: "Utah Division of Occupational & Professional Licensing (DOPL)", website: "dopl.utah.gov", notes: "EPA 608 required. NASCLA member." },
    "Vermont": { required: true, licenseType: "HVAC Contractor License", board: "VT Office of Professional Regulation", website: "sos.vermont.gov/opr", notes: "EPA 608 required." },
    "Virginia": { required: true, licenseType: "HVAC Contractor — Class A/B/C", board: "VA Board for Contractors (DPOR)", website: "dpor.virginia.gov", notes: "NASCLA member. EPA 608 required." },
    "Washington": { required: true, licenseType: "Specialty Electrician License (for HVAC)", board: "WA Dept. of Labor & Industries", website: "lni.wa.gov", notes: "HVAC work requires electrician license in WA. 8,000 hrs training required. EPA 608 required." },
    "West Virginia": { required: true, licenseType: "HVAC Contractor License", board: "WV Division of Labor", website: "labor.wv.gov", notes: "EPA 608 required." },
    "Wisconsin": { required: true, licenseType: "HVAC Contractor License", board: "WI Dept. of Safety & Professional Services (DSPS)", website: "dsps.wi.gov", notes: "EPA 608 required." },
    "Wyoming": { required: false, licenseType: "Local jurisdiction only — EPA 608 required", board: "Local City/County", website: "N/A", notes: "No state HVAC license." },
    "Washington D.C.": { required: true, licenseType: "HVAC Contractor License", board: "DC DCRA", website: "dcra.dc.gov", notes: "EPA 608 required." },
  },

  // ─── ELECTRICIAN ──────────────────────────────────────────────────────────
  Electrician: {
    "Alabama": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "Alabama Electrical Contractors Board", website: "aecb.alabama.gov", notes: "All levels state licensed." },
    "Alaska": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "AK Dept. of Labor, Electrical Inspector Section", website: "labor.alaska.gov", notes: "8,000 hrs journeyman experience." },
    "Arizona": { required: true, licenseType: "Journeyman + Electrical Contractor (ROC)", board: "Arizona Registrar of Contractors + AZ Board of Technical Registration", website: "roc.az.gov", notes: "Journeyman and contractor licensed separately." },
    "Arkansas": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "AR Dept. of Labor — Electrical Section", website: "labor.arkansas.gov", notes: "4 yrs apprentice → journeyman, 1 yr journeyman → master." },
    "California": { required: true, licenseType: "C-10 Electrical Contractor License + Certified Electrician", board: "CA Contractors State License Board (CSLB)", website: "cslb.ca.gov", notes: "8,000 hrs experience for certified electrician. C-10 for contractors." },
    "Colorado": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "CO DORA — Electrical Board", website: "dora.colorado.gov/electrical", notes: "State licenses electricians unlike GC." },
    "Connecticut": { required: true, licenseType: "E-1 / E-2 Electrical Contractor", board: "CT Dept. of Consumer Protection", website: "portal.ct.gov/DCP", notes: "Multiple classifications for residential and commercial." },
    "Delaware": { required: true, licenseType: "Journeyman + Master Electrician", board: "Delaware Division of Professional Regulation", website: "dpr.delaware.gov", notes: "Biennial renewal." },
    "Florida": { required: true, licenseType: "Certified Electrical Contractor (EC) or Registered", board: "FL DBPR — Electrical Contractors Licensing Board", website: "myfloridalicense.com", notes: "Certified = statewide. Registered = local. $100,000 GL required." },
    "Georgia": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "Georgia State Electrical Board", website: "sos.ga.gov", notes: "All levels required statewide." },
    "Hawaii": { required: true, licenseType: "Journeyman + Master Electrician (Specialty Contractor)", board: "Hawaii DCCA Contractors License Board", website: "cca.hawaii.gov/pvl", notes: "No reciprocity with any state." },
    "Idaho": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "Idaho Division of Building Safety — Electrical Bureau", website: "dbs.idaho.gov", notes: "State licenses electricians despite no GC license." },
    "Illinois": { required: true, licenseType: "Licensed Electrical Contractor (state) + local Journeyman", board: "IL Capital Development Board + Local Boards", website: "illinois.gov/cdb", notes: "State contractor license. Many cities license journeymen locally." },
    "Indiana": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state electrician license. Indianapolis and other cities have local requirements." },
    "Iowa": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "Iowa Dept. of Public Health — Electrical", website: "idph.iowa.gov", notes: "Reciprocity with several neighboring states." },
    "Kansas": { required: true, licenseType: "Journeyman + Master Electrician", board: "Kansas State Board of Technical Professions", website: "ksbtp.ks.gov", notes: "State licenses electricians despite no GC license." },
    "Kentucky": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "KY Dept. of Housing, Buildings & Construction", website: "dhbc.ky.gov", notes: "All levels required." },
    "Louisiana": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "Louisiana State Licensing Board for Contractors (LSLBC)", website: "lslbc.louisiana.gov", notes: "NASCLA member. Must employ licensed master electrician." },
    "Maine": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "Maine Electricians' Examining Board", website: "maine.gov/pfr", notes: "State licenses electricians." },
    "Maryland": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "Maryland Dept. of Labor — Electrical Licensing", website: "dllr.state.md.us", notes: "MHIC covers residential. Separate electrical board for contractors." },
    "Massachusetts": { required: true, licenseType: "Apprentice / Journeyman / Master Electrician", board: "MA Board of State Examiners of Electricians", website: "mass.gov/electricians", notes: "Master required to contract independently." },
    "Michigan": { required: true, licenseType: "Journeyman + Master Electrician + Electrical Contractor", board: "Michigan LARA — Bureau of Construction Codes", website: "michigan.gov/lara", notes: "All levels state licensed." },
    "Minnesota": { required: true, licenseType: "Apprentice / Journeyman / Master Electrician", board: "MN Dept. of Labor & Industry — Electrical", website: "dli.mn.gov/electrical", notes: "All levels state licensed." },
    "Mississippi": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "Mississippi State Board of Contractors", website: "msboc.us", notes: "State license required for $10,000+ residential, $50,000+ commercial." },
    "Missouri": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "St. Louis and Kansas City have local electrician licensing." },
    "Montana": { required: true, licenseType: "Apprentice / Journeyman / Master Electrician", board: "Montana Dept. of Labor & Industry — Electrical Board", website: "dli.mt.gov", notes: "All levels state licensed." },
    "Nebraska": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "Nebraska State Electrical Division", website: "electrical.nebraska.gov", notes: "All levels state licensed." },
    "Nevada": { required: true, licenseType: "Journeyman + Master Electrician + C-2 Electrical Contractor", board: "Nevada State Contractors Board + State Electrical Board", website: "nscb.nv.gov", notes: "Dual licensing." },
    "New Hampshire": { required: true, licenseType: "Journeyman + Master Electrician", board: "NH Office of Professional Licensure & Certification", website: "oplc.nh.gov", notes: "All levels state licensed." },
    "New Jersey": { required: true, licenseType: "Electrical Contractor License", board: "NJ Dept. of Community Affairs", website: "nj.gov/dca", notes: "Must employ licensed master electrician." },
    "New Mexico": { required: true, licenseType: "EE-98 Electrical Contractor License + Journeyman", board: "NM Regulation & Licensing Dept.", website: "rld.state.nm.us", notes: "Multiple classifications." },
    "New York": { required: true, licenseType: "Licensed Master Electrician (NYC and local jurisdictions)", board: "NYC Dept. of Buildings + Local Boards", website: "nyc.gov/buildings", notes: "No statewide electrician license. NYC requires Licensed Master Electrician with $50,000 insurance." },
    "North Carolina": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "NC Electrical Contractors Licensing Board", website: "ncel.org", notes: "All levels required statewide." },
    "North Dakota": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "ND State Electrical Board", website: "electrical.nd.gov", notes: "All levels state licensed." },
    "Ohio": { required: true, licenseType: "Electrical Contractor License (OCILB)", board: "Ohio Construction Industry Licensing Board (OCILB)", website: "com.ohio.gov/ocilb", notes: "State electrical license required via OCILB." },
    "Oklahoma": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "Oklahoma Construction Industries Board", website: "cib.ok.gov", notes: "All levels state licensed." },
    "Oregon": { required: true, licenseType: "Apprentice / Journeyman / Supervising Electrician + Contractor (CCB)", board: "Oregon CCB + Oregon Electrical Board", website: "oregon.gov/ccb", notes: "Dual licensing. 16-hr prelicense course for CCB." },
    "Pennsylvania": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No statewide electrician license. Philadelphia requires separate electrical contractor license." },
    "Rhode Island": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "RI Contractors' Registration & Licensing Board", website: "crb.ri.gov", notes: "All levels state licensed." },
    "South Carolina": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "SC Contractor's Licensing Board", website: "llr.sc.gov/clb", notes: "NASCLA member." },
    "South Dakota": { required: true, licenseType: "Journeyman + Master Electrician", board: "SD Electrical Commission", website: "dlr.sd.gov/electrical", notes: "State licenses electricians despite no GC license." },
    "Tennessee": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "TN Board for Licensing Contractors + State Fire Marshal", website: "tn.gov/commerce", notes: "NASCLA member. $25,000+ commercial requires contractor license." },
    "Texas": { required: true, licenseType: "Apprentice / Journeyman / Master Electrician + Contractor", board: "Texas Dept. of Licensing & Regulation (TDLR)", website: "tdlr.texas.gov", notes: "Despite no GC state license, electricians MUST have TDLR license." },
    "Utah": { required: true, licenseType: "Apprentice / Journeyman / Master Electrician + Contractor", board: "Utah Division of Occupational & Professional Licensing (DOPL)", website: "dopl.utah.gov", notes: "NASCLA member. All levels required." },
    "Vermont": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "VT Dept. of Public Safety — Electrical Safety", website: "firesafety.vermont.gov/electrical", notes: "All levels state licensed." },
    "Virginia": { required: true, licenseType: "Journeyman + Master Electrician + Class A/B/C Contractor", board: "VA Board for Contractors (DPOR)", website: "dpor.virginia.gov", notes: "NASCLA member." },
    "Washington": { required: true, licenseType: "Journey Level + Master Electrician + Contractor", board: "WA Dept. of Labor & Industries — Electrical", website: "lni.wa.gov/electrical", notes: "8,000 hrs training + apprenticeship required. $30,000 surety bond." },
    "West Virginia": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "WV Division of Labor", website: "labor.wv.gov", notes: "All levels state licensed." },
    "Wisconsin": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "WI Dept. of Safety & Professional Services (DSPS)", website: "dsps.wi.gov", notes: "All levels state licensed." },
    "Wyoming": { required: true, licenseType: "Journeyman + Master Electrician + Contractor", board: "WY Dept. of Fire Prevention & Electrical Safety", website: "wyomingfireelectric.com", notes: "State licenses electricians despite no GC license." },
    "Washington D.C.": { required: true, licenseType: "Journeyman + Master Electrician", board: "DC DCRA", website: "dcra.dc.gov", notes: "8,000 hrs documented experience for journeyman." },
  },

  // ─── ROOFING ───────────────────────────────────────────────────────────────
  Roofing: {
    "Alabama": { required: true, licenseType: "Roofing Contractor License ($10,000+ residential, $50,000+ commercial)", board: "Alabama Licensing Board for General Contractors", website: "albgc.alabama.gov", notes: "Covered under GC specialty classification for roofing." },
    "Alaska": { required: true, licenseType: "General Contractor License with Roofing Endorsement", board: "AK DCCED", website: "commerce.alaska.gov", notes: "All contractors require license in Alaska." },
    "Arizona": { required: true, licenseType: "C-39 Roofing Contractor License", board: "Arizona Registrar of Contractors (ROC)", website: "roc.az.gov", notes: "Separate roofing contractor classification." },
    "Arkansas": { required: true, licenseType: "Roofing Contractor License ($2,000+ residential)", board: "AR Contractors Licensing Board", website: "aclb.arkansas.gov", notes: "Home improvement license for residential under $50,000." },
    "California": { required: true, licenseType: "C-39 Roofing Contractor License", board: "CA Contractors State License Board (CSLB)", website: "cslb.ca.gov", notes: "4 yrs experience. $1,000+ project threshold." },
    "Colorado": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license. Denver and other cities have local requirements." },
    "Connecticut": { required: true, licenseType: "Home Improvement Contractor Registration (residential)", board: "CT Dept. of Consumer Protection", website: "portal.ct.gov/DCP", notes: "Registration required for residential roofing." },
    "Delaware": { required: true, licenseType: "Home Improvement Contractor License", board: "Delaware Division of Revenue", website: "revenue.delaware.gov", notes: "License covers roofing contractors." },
    "Florida": { required: true, licenseType: "Certified Roofing Contractor (CC) or Registered", board: "FL DBPR — Construction Industry Licensing Board", website: "myfloridalicense.com", notes: "Certified = statewide. $300,000 GL required for roofing. Separate classification from GC." },
    "Georgia": { required: true, licenseType: "Roofing Contractor License", board: "GA State Licensing Board", website: "sos.ga.gov", notes: "Separate classification for roofing above $2,500." },
    "Hawaii": { required: true, licenseType: "Specialty Contractor — Roofing (C-22)", board: "Hawaii DCCA Contractors License Board", website: "cca.hawaii.gov/pvl", notes: "All work over $1,000 or requiring permit needs license." },
    "Idaho": { required: false, licenseType: "Registration with Idaho Contractors Board", board: "Idaho Contractors Board", website: "dbs.idaho.gov", notes: "Registration required for $2,000+ projects. No separate roofing license." },
    "Illinois": { required: true, licenseType: "Roofing Contractor License (state-issued)", board: "IL Dept. of Financial & Professional Regulation", website: "idfpr.com", notes: "Illinois Roofing Industry Licensing Act — one of the only trades requiring state license despite no GC license." },
    "Indiana": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license. Check local requirements." },
    "Iowa": { required: false, licenseType: "Registration with Iowa Division of Labor", board: "Iowa Division of Labor", website: "iwd.iowa.gov", notes: "No separate roofing license. Registration only." },
    "Kansas": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license." },
    "Kentucky": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license. Louisville has local requirements." },
    "Louisiana": { required: true, licenseType: "Roofing Contractor License ($7,500+ home improvement)", board: "Louisiana State Licensing Board for Contractors (LSLBC)", website: "lslbc.louisiana.gov", notes: "Home improvement registration for $7,500–$75,000. Contractor license for $75,000+." },
    "Maine": { required: false, licenseType: "No state license — written contract required for $3,000+", board: "N/A", website: "N/A", notes: "No state roofing license." },
    "Maryland": { required: true, licenseType: "Home Improvement Contractor License (MHIC)", board: "Maryland Home Improvement Commission (MHIC)", website: "dllr.state.md.us/license/mhic", notes: "All residential improvement including roofing." },
    "Massachusetts": { required: true, licenseType: "Home Improvement Contractor (HIC) Registration", board: "MA Office of Consumer Affairs & Business Regulation", website: "mass.gov/hic", notes: "All residential roofing." },
    "Michigan": { required: true, licenseType: "Residential Builder License or Maintenance & Alteration Contractor", board: "Michigan LARA", website: "michigan.gov/lara", notes: "Covers residential roofing." },
    "Minnesota": { required: true, licenseType: "Residential Remodeler or Residential Building Contractor", board: "MN Dept. of Labor & Industry", website: "dli.mn.gov", notes: "Roofing falls under residential remodeler classification." },
    "Mississippi": { required: true, licenseType: "Roofing Contractor License ($10,000+ residential)", board: "Mississippi State Board of Contractors", website: "msboc.us", notes: "NASCLA member." },
    "Missouri": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "St. Louis and Kansas City have local requirements." },
    "Montana": { required: false, licenseType: "No state license — registration if employees", board: "MT Dept. of Labor & Industry", website: "dli.mt.gov", notes: "No state roofing license." },
    "Nebraska": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license." },
    "Nevada": { required: true, licenseType: "C-15 Roofing Contractor License", board: "Nevada State Contractors Board", website: "nscb.nv.gov", notes: "Separate roofing classification." },
    "New Hampshire": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license." },
    "New Jersey": { required: true, licenseType: "Home Improvement Contractor Registration", board: "NJ Division of Consumer Affairs", website: "njconsumeraffairs.gov", notes: "All residential roofing." },
    "New Mexico": { required: true, licenseType: "GS-8 Roofing Contractor License", board: "NM Construction Industries Division", website: "rld.state.nm.us/construction", notes: "Separate roofing classification." },
    "New York": { required: true, licenseType: "Home Improvement Contractor Registration (HICPA)", board: "NY Division of Consumer Protection", website: "dos.ny.gov", notes: "NYC has additional local roofing requirements." },
    "North Carolina": { required: true, licenseType: "Roofing Contractor License", board: "NC Licensing Board for General Contractors", website: "nclbgc.org", notes: "Tiered by project value." },
    "North Dakota": { required: true, licenseType: "Contractor License ($4,000+)", board: "ND Secretary of State", website: "sos.nd.gov", notes: "Low threshold." },
    "Ohio": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "Columbus, Cleveland, Cincinnati have local roofing registration requirements." },
    "Oklahoma": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license." },
    "Oregon": { required: true, licenseType: "Residential or Commercial Roofing (CCB)", board: "Oregon Construction Contractors Board (CCB)", website: "oregon.gov/ccb", notes: "NASCLA member. 16-hr prelicense course." },
    "Pennsylvania": { required: true, licenseType: "Home Improvement Contractor Registration (HICPA)", board: "PA Office of Attorney General", website: "attorneygeneral.gov", notes: "All residential roofing." },
    "Rhode Island": { required: true, licenseType: "Contractor Registration", board: "RI Contractors' Registration & Licensing Board", website: "crb.ri.gov", notes: "Covers roofing contractors." },
    "South Carolina": { required: true, licenseType: "Roofing Contractor License (RBC or CLB)", board: "SC Residential Builders Commission or CLB", website: "llr.sc.gov", notes: "NASCLA member." },
    "South Dakota": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license." },
    "Tennessee": { required: true, licenseType: "Roofing Contractor License ($3,000+)", board: "TN Board for Licensing Contractors", website: "tn.gov/commerce/boards/contractors", notes: "NASCLA member." },
    "Texas": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license. Dallas, Houston, Austin have local requirements." },
    "Utah": { required: true, licenseType: "Roofing Contractor License", board: "Utah Division of Occupational & Professional Licensing (DOPL)", website: "dopl.utah.gov", notes: "NASCLA member." },
    "Vermont": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license." },
    "Virginia": { required: true, licenseType: "Class A/B/C Roofing Contractor", board: "VA Board for Contractors (DPOR)", website: "dpor.virginia.gov", notes: "NASCLA member. $1,000+ threshold." },
    "Washington": { required: true, licenseType: "General Contractor Registration + Roofing Endorsement", board: "WA Dept. of Labor & Industries", website: "lni.wa.gov", notes: "$30,000 surety bond required." },
    "West Virginia": { required: true, licenseType: "Roofing Contractor License", board: "WV Division of Labor", website: "labor.wv.gov", notes: "NASCLA member." },
    "Wisconsin": { required: true, licenseType: "Dwelling Contractor Qualifier (DCQ) for residential roofing", board: "WI Dept. of Safety & Professional Services (DSPS)", website: "dsps.wi.gov", notes: "DCQ covers residential roofing." },
    "Wyoming": { required: false, licenseType: "Local jurisdiction only", board: "Local City/County", website: "N/A", notes: "No state roofing license." },
    "Washington D.C.": { required: true, licenseType: "Home Improvement Contractor License", board: "DC DCRA", website: "dcra.dc.gov", notes: "Covers roofing contractors." },
  },

  // ─── SPECIALTY ─────────────────────────────────────────────────────────────
  Specialty: {
    note: "Specialty trades (Painter, Flooring, Drywall, Tile, Carpenter, Landscaping, Appliance Repair, Locksmith, Garage Door, Pest Control, Pressure Washing, Fence & Deck, Window & Door, Insulation) generally fall under Home Improvement Contractor or General Contractor licensing. They do NOT require the same trade-specific licenses as Plumber, Electrician, HVAC, or Roofing.",
    general: {
      statesWithRegistration: ["Connecticut", "Delaware", "Florida", "Georgia", "Maryland", "Massachusetts", "Michigan", "Minnesota", "New Jersey", "New York", "Pennsylvania", "Rhode Island", "Wisconsin"],
      statesLocalOnly: ["Colorado", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Maine", "Missouri", "Montana", "Nebraska", "New Hampshire", "Ohio", "Oklahoma", "South Dakota", "Texas", "Vermont", "Wyoming"],
      statesWithFullLicense: ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Hawaii", "Louisiana", "Mississippi", "Nevada", "New Mexico", "North Carolina", "Oregon", "South Carolina", "Tennessee", "Utah", "Virginia", "Washington", "West Virginia"],
    },
    keyNotes: [
      "Pest Control: Requires separate state pesticide applicator license in ALL 50 states — regulated by state dept of agriculture",
      "Locksmith: 15 states require a locksmith license (AL, CA, CT, IL, LA, MD, NC, NJ, NV, OK, OR, TN, TX, VA, WA)",
      "Landscaping/Irrigation: Most states require pesticide license for chemical application. Irrigation may require plumbing license for backflow prevention.",
      "Appliance Repair: Generally no separate license required — covered under handyman or GC license",
      "Painter: Most states no separate license — covered under home improvement contractor registration",
      "Always verify with local city/county as requirements vary significantly for specialty trades"
    ]
  }
};

// ─── HELPER FUNCTIONS ────────────────────────────────────────────────────────

// Get license info for a specific trade and state
export const getTradeLicense = (trade, state) => {
  const tradeData = TRADE_LICENSE_DATA[trade];
  if (!tradeData) return null;
  return tradeData[state] || null;
};

// Get all trades that require a license in a given state
export const getRequiredLicensesByState = (state) => {
  const trades = ['Plumber', 'HVAC', 'Electrician', 'Roofing'];
  return trades.filter(trade => {
    const data = TRADE_LICENSE_DATA[trade]?.[state];
    return data?.required === true;
  });
};

// Check if EPA 608 is required (always true for HVAC)
export const requiresEPA608 = (trade) => trade === 'HVAC';

export default TRADE_LICENSE_DATA;
